services:
  mongo:
    image: mongo:8.0
    container_name: rapidcron-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo@12
    volumes:
      - mongo_data:/data/db

  etcd:
    image: quay.io/coreos/etcd:v3.5.16
    container_name: rapidcron-etcd
    ports:
      - "2379:2379"
    command: etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rapidcron-rabbitmq
    ports:
      - "5672:5672"     # AMQP 协议
      - "15672:15672"   # Web 管理界面
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbitmq_data: